-- Creación de la base de datos
CREATE DATABASE ProyectoMovilidad;
GO

-- Usar la base de datos
USE ProyectoMovilidad;
GO


-- TABLA CIUDAD
CREATE TABLE CIUDAD (
    ID_CIUDAD INT IDENTITY(1,1) PRIMARY KEY,
    COORDENADA_CIUDAD NVARCHAR(40) NOT NULL,
    DEPARTAMENTO_CIUDAD NVARCHAR(90) NOT NULL,
    CANTIDADHABITANTES_CIUDAD NVARCHAR(8) NOT NULL,
    DIVISIONTERRITORIAL_CIUDAD NVARCHAR(20) NOT NULL,
    NOMBRE_CIUDAD NVARCHAR(50) NOT NULL
);
GO

--TABLA EVENTO ESNI
CREATE TABLE EVENTO (
    ID_EVENTO INT IDENTITY(1,1) PRIMARY KEY,
    OBRAS_EVENTO NVARCHAR(60) NOT NULL,
    PROTESTAS_EVENTO NVARCHAR(60) NOT NULL,
    CIERREVIAS_EVENTO NVARCHAR(50) NOT NULL,
    CONCIERTO_EVENTO NVARCHAR(60) NOT NULL,
    NAVIDAD_EVENTO NVARCHAR(60) NOT NULL,
    DIAMADRE_EVENTO NVARCHAR(60) NOT NULL,
    ACCIDENTE_EVENTO NVARCHAR(60) NOT NULL
);
GO

--TABLA VEHICULO ESNI
CREATE TABLE VEHICULO (
    ID_VEHICULO INT IDENTITY(1,1) PRIMARY KEY,
    PLACA_VEHICULO NVARCHAR(6) NOT NULL,
    MARCA_VEHICULO NVARCHAR(30) NOT NULL,
    TIPO_VEHICULO NVARCHAR(30) NOT NULL,
    MODELO_VEHICULO NVARCHAR(4) NOT NULL
);
GO


--TABLA PREDICCION ESNI
CREATE TABLE PREDICCION (
    ID_PREDICCION INT IDENTITY(1,1) PRIMARY KEY,
    HORA_PREDICCION NVARCHAR(8) NOT NULL,
    FECHA_PREDICCION NVARCHAR(8) NOT NULL,
    ID_USUARIO_PREDICCION INT (7),
    ID_VEHICULO_PREDICCION INT (7),
    FOREIGN KEY (ID_USUARIO) REFERENCES (ID_USUARIO),
    FOREIGN KEY (ID_VEHICULO) REFERENCES (ID_VEHICULO)

);
GO

--TABLA RUTA DD

CREATE TABLE RUTA (
    ID_RUTA INT IDENTITY(1,1) PRIMARY KEY,
    DESCRIPCION_RUTA NVARCHAR(200) NOT NULL
);
GO

-- TABLA BARRIO DD
CREATE TABLE BARRIO (
    ID_BARRIO INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE_BARRIO NVARCHAR(50) NOT NULL,
    SUPERFICIE_BARRIO NVARCHAR(50) NOT NULL,
    ID_CIUDAD INT,
    ESTRATO_BARRIO NVARCHAR(5) NOT NULL,
    TIPO_BARRIO NVARCHAR(20) NOT NULL,
    FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD(ID_CIUDAD)
);
GO

--TABLA UBICACION DD

CREATE TABLE UBICACION (
    ID_UBICACION INT IDENTITY(1,1) PRIMARY KEY,
    ID_CIUDAD INT,
    ID_TRAMO INT,
    ID_PARQUEADERO INT,
    SENTIDO_UBICACION NVARCHAR(20) NOT NULL,
    ALTURA_UBICACION NVARCHAR(20) NOT NULL,
    DESCRIPCION_UBICACION NVARCHAR(100) NOT NULL,
    COORDENADA_UBICACION NVARCHAR(50) NOT NULL,
    FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD(ID_CIUDAD),
    FOREIGN KEY (ID_TRAMO) REFERENCES TRAMO(ID_TRAMO),
    FOREIGN KEY (ID_PARQUEADERO) REFERENCES PARQUEADERO(ID_PARQUEADERO)
);
GO

--TABLA SENALTRANSITO DD

CREATE TABLE SENALTRANSITO (
    ID_SENALTRANSITO INT IDENTITY(1,1) PRIMARY KEY,
    ID_UBICACION INT,
    OBRA_SENAL NVARCHAR(50) NOT NULL,
    TIPO_SENAL NVARCHAR(50) NOT NULL,
    FOREIGN KEY (ID_UBICACION) REFERENCES UBICACION(ID_UBICACION),
    FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDAD(ID_CIUDAD)
);
GO

--TABLA TRAMO DD

CREATE TABLE TRAMO (
    TRAMOID INT IDENTITY(1,1) PRIMARY KEY,
    ID_RUTA INT,
    ID_UBICACION INT,
    VELOCIDAD_TRAMO NVARCHAR(20) NOT NULL,
    PARTIDA_TRAMO NVARCHAR(50) NOT NULL,
    LLEGADA_TRAMO NVARCHAR(50) NOT NULL,
    DESCRIPCION_TRAMO NVARCHAR(100) NOT NULL,
    FOREIGN KEY (ID_RUTA) REFERENCES RUTA(ID_RUTA),
    FOREIGN KEY (ID_UBICACION) REFERENCES UBICACION(ID_UBICACION)
);
GO

--TABLA PARQUEADERO 
CREATE TABLE PARQUEADERO (
    ID_PARQUEADERO INT IDENTITY(1,1) PRIMARY KEY,
    CAPACIDAD_PARQUEADERO NVARCHAR(5) NOT NULL,
    TARIFA_PARQUEADERO NVARCHAR(6) NOT NULL,
    DISPONIBILIDAD_PARQUEADERO NVARCHAR(10) NOT NULL,
    UBICACION_PARQUEADERO NVARCHAR(50)
);
GO

--TABLA TIEMPO 
CREATE TABLE TIEMPO (
    ID_TIEMPO INT IDENTITY(1,1) PRIMARY KEY,
    HORAPICOVALLE_TIEMPO NVARCHAR(6) NOT NULL,
    DIASEMANA_TIEMPO NVARCHAR(10) NOT NULL,
    CLIMA_TIEMPO NVARCHAR(50) NOT NULL
);
GO

--TABLA USUARIO
CREATE TABLE USUARIO (
    ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY,
    EDAD_USUARIO NVARCHAR (2) NOT NULL,
    DOCUMENTO_USUARIO NVARCHAR(7) NOT NULL,
    NOMBRE_USUARIO NVARCHAR(50) NOT NULL,
    TIPO_USUARIO NVARCHAR(10) NOT NULL,
    GENERO_USUARIO NVARCHAR(15) NOT NULL,
    CORREO_USUARIO NVARCHAR(50) NOT NULL
);
GO


--TABLA CIUDADUSUARIO
CREATE TABLE CIUDADUSUARIO (
    ID_CIUDADUSUARIO INT IDENTITY(1,1) PRIMARY KEY,
    ID_CIUDADUSUARIO INT,
    ID_USUARIO INT,
    DESCRIPCION_CIUDADUSUARIO NVARCHAR(200) NOT NULL,
    FOREIGN KEY (ID_CIUDADUSUARIO) REFERENCES Ciudad(ID_CIUDADUSUARIO),
    FOREIGN KEY (ID_USUARIO) REFERENCES Usuario(ID_USUARIO)

);
GO

--TABLA VEHICULOUSUARIO
CREATE TABLE VEHICULOUSUARIO (
    ID_VEHICULOUSUARIO INT IDENTITY(1,1) PRIMARY KEY,
    ID_VEHICULO INT,
    ID_USUARIO INT,
    DESCRIPCION_VEHICULOUSUARIO NVARCHAR(200) NOT NULL,
    FOREIGN KEY (ID_VEHICULO) REFERENCES Vehiculo(ID_VEHICULO),
    FOREIGN KEY (ID_USUARIO) REFERENCES Usuario(ID_USUARIO)
);
GO

--TABLA VEHICULOPARQUEADERO 
CREATE TABLE VEHICULOPARQUEADERO (
    ID_VEHICULOPARQUEADERO INT IDENTITY(1,1) PRIMARY KEY,
    ID_VEHICULO INT,
    ID_PARQUEADERO INT,
    DESCRIPCION_VEHICULOPARQUEADERO NVARCHAR (200) NOT NULL,
    FOREIGN KEY (ID_VEHICULO) REFERENCES Vehiculo(ID_VEHICULO),
    FOREIGN KEY (ID_PARQUEADERO) REFERENCES Parqueadero(ID_PARQUEADERO)
);
GO
-- TABLA CIUDADEVENTO 
CREATE TABLE CIUDADEVENTO  (
    ID_CIUDADEVENTO INT IDENTITY(1,1) PRIMARY KEY,
    ID_CIUDAD INT,
    ID_EVENTO INT, 
    DESCRIPCION_CIUDADEVENTO NVARCHAR (200) NOT NULL 

);

--Insertar datos de ejemplo para Bogotá
INSERT INTO Ciudad (Coordenada_Ciudad, Departamento_Ciudad, CantidadHabitante_Ciudad, Divisionterritorial_Ciudad, Nombre_Ciudad)
VALUES ('56775', 'Bogotá D.C.', '4565565', 'FGH', 'BOGOTÁ D.C.');
GO
